coverage:
  range: 70..100
  round: down
  precision: 0

  status:
    project:
      default:
        # basic
        target: 30%

  ignore:
    - "mock"
    - "config"
    - "tests"
    - "services"
    - "scripts"
    - "docs"
    - "db/models"
