# Gin is the web framework
gin:
  # Possible values: "debug", "release"
  mode: release
  # App running behind a reverse proxy?
  # If set, HTTP Forwarded headers will be respected
  reverse_proxy: false

# If all - run all platforms in one binary. You can pick specific coin handle to run binary only with specific coin
# Example: ethereum
# You can see all the coin handles at coins/coins.yml file
platform: all

# Sentry error tracking
#sentry:
#  dsn: https://xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx@sentry.io/xxxxxxx

# The transaction watcher
observer:
  backlog: 3h
  # Don't request more than N blocks at once
  backlog_max_blocks: 200
  # Max connections to open to API
  stream_conns: 16
  # Block polling interval
  block_poll:
    min: 3s
    max: 30s
  rabbitmq:
    uri: amqp://rabbit:5672
    consumer:
      prefetch_count: 10

postgres:
  uri: postgresql://user:pass@localhost/my_db?sslmode=disable

# [BNB] Binance DEX: https://wallet.binance.org
#       Binance Chain: https://explorer.binance.org
binance:
  api: http://localhost:3000/binance-api/v1
  dex: https://dex.binance.org/api

# [NIM] Nimiq: https://nimiq.com
nimiq:
  api: http://localhost:3000/nimiq-rpc

# [XRP] Ripple: https://ripple.com
ripple:
  api: http://localhost:3000/ripple-api

# [XLM] Stellar Lumen: https://www.stellar.org
stellar:
  api: http://localhost:3000/stellar-api

# [KIN] Kin: https://www.kin.org
kin:
  api: http://localhost:3000/kin-api

# [XTZ] Tezos: https://tezos.com
tezos:
  api: http://localhost:3000/tezos-api
  rpc: https://mainnet.tezos.org.ua

# [ETH] Ethereum: https://ethereum.org (Trust-Ray API)
ethereum:
  api: http://localhost:3000/eth-api
  blockbook_api: http://localhost:3000/eth-blockbook-api
  collections_api: https://api.opensea.io
  collections_api_key: opensea_api_key
  rpc: http://localhost:3000/eth-rpc

# [ETC] Ethereum Classic: https://ethereumclassic.org (Trust-Ray API)
classic:
  api: http://localhost:3000/ethclassic-api

# [POA] POA Network: https://poa.network (Trust-Ray API)
poa:
  api: http://localhost:3000/poa-api

# [CLO] Callisto Network: https://callisto.network (Trust-Ray API)
callisto:
  api: http://localhost:3000/callisto-api

# [GO] GoChain: https://gochain.io (Trust-Ray API)
gochain:
  api: http://localhost:3000/gochain-api

# [WAN] Wanchain: https://wanchain.org (Trust-Ray API)
# wanchain:
#   api: https://localhost:4567

# [TOMO] TomoChain: https://tomochain.com (Trust-Ray API)
tomochain:
  api: http://localhost:3000/tomochain-api

# [TT] ThunderCore: https://www.thundercore.com (Trust-Ray API)
thundertoken:
  api: http://localhost:3000/thundertoken-api

# [AION] Aion: https://aion.network
aion:
  api: http://localhost:3000/aion-api

# [ICX] ICON: https://icon.foundation
icon:
  api: http://localhost:3000/icon-api

# [TRX] Tron: https://tron.network/
tron:
  api: http://localhost:3000/tron-api

# [VET] VeChain: https://www.vechain.org
vechain:
  api: http://localhost:3000/vechain-api

# [THETA] THETA: https://www.thetatoken.org/
theta:
  api: http://localhost:3000/theta-api

# [ATOM] Cosmos: https://cosmos.network/
cosmos:
  api: http://localhost:3000/cosmos-api

# [ONTOLOGY] ONT: https://ont.io/
ontology:
  api: http://localhost:3000/ontology-api

# [ZIL] Zilliqa: https://zilliqa.com
zilliqa:
  api: http://localhost:3000/zilliqa-api
  # key: YOUR_API_KEY
  rpc: https://api.zilliqa.com
  lookup: http://localhost:3000/unstoppabledomains/api/v1

#[IoTeX] IoTeX: https://iotex.io
iotex:
  api: http://localhost:3000/iotex-api

# [WAVES] Waves: http://wavesplatform.com
waves:
  api: http://localhost:3000/waves-api

# [AE] Aeternity: https://aeternity.com
aeternity:
  api: http://localhost:3000/aeternity-api

# [NAS] Nebulas: https://nebulas.io
nebulas:
  api: http://localhost:3000/nebulas-api

fio:
  api: http://localhost:3000/fio-api

# [BTC] Bitcoin: https://bitcoin.org/ (Blockbook API https://github.com/trezor/blockbook)
bitcoin:
  api: http://localhost:3000/bitcoin-api

litecoin:
  api: http://localhost:3000/litecoin-api

bitcoincash:
  api: http://localhost:3000/bitcoincash-api

doge:
  api: http://localhost:3000/doge-api

dash:
  api: http://localhost:3000/dash-api

zcoin:
  api: http://localhost:3000/zcoin-api

zcash:
  api: http://localhost:3000/zcash-api

zelcash:
  api: http://localhost:3000/zelcash-api

viacoin:
  api: http://localhost:3000/viacoin-api

qtum:
  api: http://localhost:3000/qtum-api

groestlcoin:
  api: http://localhost:3000/groestlcoin-api

ravencoin:
  api: http://localhost:3000/ravencoin-api

decred:
  api: http://localhost:3000/decred-api

algorand:
  api: http://localhost:3000/algorand-api

nano:
  api: http://localhost:3000/nano-api

digibyte:
  api: http://localhost:3000/digibyte-api

harmony:
  api: http://localhost:3000/harmony-api

kava:
  api: http://localhost:3000/kava-api

kusama:
  api: http://localhost:3000/kusama-rpc
